# Generated by Django 3.0.6 on 2020-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTC_POST_TB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('postDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('postBy', models.CharField(max_length=255)),
                ('uuidPost', models.CharField(max_length=36)),
            ],
        ),
    ]
