# Generated by Django 3.0.6 on 2020-06-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttc_rest_api', '0003_auto_20200615_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttc_comment_tb',
            old_name='post',
            new_name='uuidPost',
        ),
    ]
